export { default as Section1 } from './parts/Section1'
export { default as Main } from './parts/Main'
export { default as LockScreen } from './parts/LockScreen'
export { default as CountDown } from './ui/CountDown'
export { default as Modal } from './ui/Modal'
export { default as ItemInstruksi } from './ui/ItemInstruksi'
